# -*- coding: utf-8 -*-
"""to-do simple app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0ssEdBLwufJ_CayJ2dVx5abbkA2stsl
"""

pip install streamlit

import streamlit as st

st.set_page_config(page_title="✅ To-Do with Completion", layout="centered")

st.title("✅ Advanced To-Do List App")

# Initialize session state
if "tasks" not in st.session_state:
    st.session_state.tasks = []

# Task format: {"task": str, "done": bool}

# Add new task
with st.form(key="add_task_form"):
    new_task = st.text_input("New Task")
    submit = st.form_submit_button("Add Task")
    if submit and new_task:
        st.session_state.tasks.append({"task": new_task, "done": False})
        st.success("Task added!")

# Display and update tasks
st.subheader("🗒️ Your Tasks")

if not st.session_state.tasks:
    st.info("No tasks added yet.")
else:
    for i, task_obj in enumerate(st.session_state.tasks):
        col1, col2 = st.columns([0.1, 0.9])
        done = col1.checkbox("", value=task_obj["done"], key=f"task_{i}")
        st.session_state.tasks[i]["done"] = done

        task_text = task_obj["task"]
        if done:
            col2.markdown(f"<del>{task_text}</del>", unsafe_allow_html=True)
        else:
            col2.markdown(task_text)

# Clear completed tasks
if any(task["done"] for task in st.session_state.tasks):
    if st.button("🧹 Remove Completed Tasks"):
        st.session_state.tasks = [task for task in st.session_state.tasks if not task["done"]]
        st.success("Completed tasks removed.")

# Optional: Clear all tasks
if st.button("🗑️ Clear All Tasks"):
    st.session_state.tasks.clear()
    st.info("All tasks cleared.")

